### ISSUE TITLE
Doesn't properly change tmux status color

### ISSUE THREAD

**Issue by chrisvanpatten** [oliamb/guard-compass#9] opened 2013-01-01 16:49 UTC
Guard has the ability to change tmux's status color on error or success. Currently, guard-compass handles errors properly and the status-color is set to red, but is not returned to green when the file is successfully written.

Presumably this is abstracted away somehow in Guard, and guard-compass just isn't sending the right signals? Hopefully this is an easy fix. It can be frustrating to get an error and be stuck with a red statusline in tmux for the rest of your session!

**Comment by rymai** [comment] 2013-10-07 22:21
Hi @chrisvanpatten, could you update Guard and guard-compass to the latest versions and verify that the issue is still there or not?

If it's still there, please [open a new issue in the maintained repository](https://github.com/guard/guard-compass/issues).

In both cases, don't forget to close this issue, thanks!

**Comment by chrisvanpatten** [comment] 2013-10-08 05:18
I've actually stopped using guard-compass in place of a custom Makefile based system. Sorry!

**Comment by rymai** [comment] 2013-10-08 10:08
Ok, no worries! Could you close this issue then? Thanks!

**Closed as completed** 2013-10-08 18:46 UTC
